sudo: required
services:
  - docker

before_install:
  - docker build -t eumb602/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eumb602/react-test npm run test -- --coverage

after_success: 
  - docker build -t eumb602/multi-client ./client
  - docker build -t eumb602/multi-nginx ./nginx
  - docker build -t eumb602/multi-server ./server
  - docker build -t eumb602/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push eumb602/multi-client
  - docker push eumb602/multi-nginx
  - docker push eumb602/multi-server
  - docker push eumb602/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-west-1-488754487905
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY